### ISSUE TITLE
Error while executing tests

### ISSUE THREAD

**Issue by petitout** [digitalpetri/opc-ua-stack#12]
Hi Kevin,
I try to install your stack but I get this message each time I type "mvn install" or "mvn package" :
```
Tests run: 192, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 113.023 sec <<< FAILURE!
testClientReconnect(com.digitalpetri.opcua.stack.ClientServerTest)  Time elapsed: 62.813 sec  <<< FAILURE!
java.util.concurrent.ExecutionException: UaException: status=Bad_Timeout, message=request timed out after 60000ms
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.digitalpetri.opcua.stack.ClientServerTest.testClientReconnect(ClientServerTest.java:300)
Caused by: UaException: status=Bad_Timeout, message=request timed out after 60000ms
	at com.digitalpetri.opcua.stack.client.UaTcpStackClient.lambda$scheduleRequestTimeout$15(UaTcpStackClient.java:264)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367)
	at java.lang.Thread.run(Thread.java:745)


Results :

Failed tests:   testClientReconnect(com.digitalpetri.opcua.stack.ClientServerTest): UaException: status=Bad_Timeout, message=request timed out after 60000ms

Tests run: 192, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OPC-UA Stack ....................................... SUCCESS [  0.002 s]
[INFO] stack-core ......................................... SUCCESS [  3.075 s]
[INFO] stack-client ....................................... SUCCESS [  0.024 s]
[INFO] stack-server ....................................... SUCCESS [  0.037 s]
[INFO] stack-examples ..................................... SUCCESS [  0.019 s]
[INFO] stack-tests ........................................ FAILURE [01:53 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:56 min
[INFO] Finished at: 2015-11-03T14:30:00-08:00
[INFO] Final Memory: 15M/430M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project stack-tests: There are test failures.
```

Thanks for your help

**Comment by kevinherron** [comment]
Hey,

The code may have been in a broken state, and I just pushed some changes that I confirmed could be built and tested, so could you update to HEAD and try again please?

**Comment by petitout** [comment]
Hi,
I pulled the new code, did a mvn clean and mvn install and now 2 tests are failing :
```
Tests run: 192, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 177.251 sec <<< FAILURE!
testClientReconnect(com.digitalpetri.opcua.stack.ClientServerTest)  Time elapsed: 62.347 sec  <<< FAILURE!
java.util.concurrent.ExecutionException: UaException: status=Bad_Timeout, message=request timed out after 60000ms
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.digitalpetri.opcua.stack.ClientServerTest.testClientReconnect(ClientServerTest.java:300)
Caused by: UaException: status=Bad_Timeout, message=request timed out after 60000ms
	at com.digitalpetri.opcua.stack.client.UaTcpStackClient.lambda$scheduleRequestTimeout$15(UaTcpStackClient.java:264)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367)
	at java.lang.Thread.run(Thread.java:745)

testClientReconnect_InvalidSecureChannel(com.digitalpetri.opcua.stack.ClientServerTest)  Time elapsed: 61.842 sec  <<< FAILURE!
java.util.concurrent.ExecutionException: UaException: status=Bad_Timeout, message=request timed out after 60000ms
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.digitalpetri.opcua.stack.ClientServerTest.testClientReconnect_InvalidSecureChannel(ClientServerTest.java:333)
Caused by: UaException: status=Bad_Timeout, message=request timed out after 60000ms
	at com.digitalpetri.opcua.stack.client.UaTcpStackClient.lambda$scheduleRequestTimeout$15(UaTcpStackClient.java:264)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367)
	at java.lang.Thread.run(Thread.java:745)


Results :

Failed tests:   testClientReconnect(com.digitalpetri.opcua.stack.ClientServerTest): UaException: status=Bad_Timeout, message=request timed out after 60000ms
  testClientReconnect_InvalidSecureChannel(com.digitalpetri.opcua.stack.ClientServerTest): UaException: status=Bad_Timeout, message=request timed out after 60000ms

Tests run: 192, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OPC-UA Stack ....................................... SUCCESS [  0.210 s]
[INFO] stack-core ......................................... SUCCESS [  7.127 s]
[INFO] stack-client ....................................... SUCCESS [  0.315 s]
[INFO] stack-server ....................................... SUCCESS [  0.262 s]
[INFO] stack-examples ..................................... SUCCESS [  0.150 s]
[INFO] stack-tests ........................................ FAILURE [02:57 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:06 min
[INFO] Finished at: 2015-11-03T15:00:00-08:00
[INFO] Final Memory: 29M/509M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project stack-tests: There are test failures.
```

**Comment by kevinherron** [comment]
Hmm. It seems the tests have some timing sensitivities I need to work out...

In the meantime, you can compile and install the using `mvn install -DskipTests`

I'll see what I can do about the test failures.

**Comment by petitout** [comment]
Alright thanks !

2015-11-03 15:56 GMT-08:00 Kevin Herron <notifications@github.com>:

**Comment by kevinherron** [comment]
When you get a chance can you update to the latest and run `mvn clean test`?

**Comment by petitout** [comment]
It works fine now

Thanks

2015-11-19 5:53 GMT-08:00 Kevin Herron <notifications@github.com>:
